name: events
run-name: Events

on:
   issues:
     types: 
        - opened


jobs:
    show-ref-and-sha:
        runs-on: ubuntu-latest
        steps:
            - name: ECHO GITHUB_SHA and GITHUB_REF
              run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
