name: manually
run-name: Workflow Manual

on:
    workflow_dispatch:
        inputs:
            message:
                description: Messagem a ser exibida no terminal
                type: string
                required: true
                default: "Olá mundo"
            logLevel:
                description: Log Level
                required: true
                default: 'warning'
                type: choice
                options:
                    - info
                    - warning
                    - debug


jobs:
    echo-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{ inputs.message }}
    log-the-inputs:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Log level: $LEVEL"
              env:
                LEVEL: ${{ inputs.logLevel }}
            